services:
  db:
    image: postgres:16
    container_name: whathappenednews_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  web:
    build:
      context: ./
      dockerfile: compose/django/Dockerfile
    container_name: whathappenednews_web
    command: uvicorn core.asgi:application --host 0.0.0.0 --port ${DJANGO_PORT} --lifespan off --workers 9
    volumes:
      - ./:/app
      - ./static:/home/app/web/static
      - ./locales:/home/app/web/locales
      - ./media:/home/app/web/media
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
