# Generated by Django 5.0.7 on 2024-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('LOAN_MANAGER', 'Loan Manager'), ('BANK_TELLER', 'Bank Teller')], default='EMPLOYEE', max_length=32),
        ),
    ]
